import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  workflows: [
    {
      type: 'category',
      label: 'Named Workflows',
      link: {type: 'doc', id: 'named-workflows/index'},
      items: [{type: 'autogenerated', dirName: 'named-workflows'}],
    },
    {
      type: 'category',
      label: 'Bactopia Tools',
      link: {type: 'doc', id: 'bactopia-tools/index'},
      items: [{type: 'autogenerated', dirName: 'bactopia-tools'}],
    },
  ],
};

export default sidebars;
