import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  developers: [
    {
      type: 'category',
      label: 'Developers',
      link: {type: 'doc', id: 'index'},
      items: [
        {
          type: 'category',
          label: 'CLI Reference',
          link: {type: 'doc', id: 'cli/index'},
          items: [{type: 'autogenerated', dirName: 'cli'}],
        },
        {
          type: 'category',
          label: 'nf-bactopia Plugin',
          link: {type: 'doc', id: 'nf-bactopia/index'},
          items: [{type: 'autogenerated', dirName: 'nf-bactopia'}],
        },
        {
          type: 'category',
          label: 'Subworkflows',
          link: {type: 'doc', id: 'subworkflows/index'},
          items: [{type: 'autogenerated', dirName: 'subworkflows'}],
        },
        {
          type: 'category',
          label: 'Modules',
          link: {type: 'doc', id: 'modules/index'},
          items: [{type: 'autogenerated', dirName: 'modules'}],
        },
      ],
    },
  ],
};

export default sidebars;
