authors:
  rpetit3:
    name: Robert A. Petit III
    description: The primary developer of Bactopia
    avatar: https://avatars.githubusercontent.com/u/5334269
    slug: rpetit3
    url: https://www.robertpetit.com/
